### ISSUE TITLE
Exception when accessing nullable object's fields

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/SyliusGridBundle#127]
**Sylius version affected**: 1.7

**Description**
When trying to display value of `customer.email` where customer is nullable, getting next exception:

```
An exception has been thrown during the rendering of a template ("PropertyAccessor requires a graph of objects or arrays to operate on, but it found type "NULL" while trying to traverse path "customer.email" at property "email".").
```

This is grid configuration:
```
sylius_grid:
    grids:
        setono_sylius_gift_card_admin_gift_card:
            fields:
                customerEmail:
                    type: string
                    label: setono_sylius_gift_card.ui.customer_email
                    path: customer.email
                    sortable: ~
```

File where exception throwing: https://github.com/Sylius/SyliusGridBundle/blob/03f8a15ef4d7d83e5e36c9bf4277ca347c925500/src/Component/DataExtractor/PropertyAccessDataExtractor.php

**Possible solution**
Fallback to empty string or null on exception

**Comment by damic88** [comment]
Possible solution @igormukhingmailcom 

```
sylius_grid:
    grids:
        setono_sylius_gift_card_admin_gift_card:
            fields:
                customerEmail:
                    type: string
                    label: setono_sylius_gift_card.ui.customer_email
                    path: customer?.email
                    sortable: ~
```
