### ISSUE TITLE
Filter option "default_value" not working with boolean filters

### ISSUE THREAD

**Issue by Geolim4** [Sylius/SyliusGridBundle#251]
Hello,

I have created a boolean filter on my project:
```yaml
sylius_grid:
    grids:
        sylius_admin_promotion:
            filters:
                archived:
                    default_value: true 
                    type: boolean
                    label: "Archived"

```

And when I'm loading the "promotions" view the filter "Archived" is not assigned to "true" but "all".
Not even working with "1" instead of boolean.

Thanks !
