### ISSUE TITLE
PHP 8.1 Enums are not working

### ISSUE THREAD

**Issue by andriusvo** [Sylius/SyliusGridBundle#252]
PHP 8.1 Enums are not working as grid arguments. F.e.:

```
repository:
    method: createFooBuilder
    arguments:
           - !php/const App\Enums\FooEnum::FOO
```
 
Warning is raised from PHP side that 'sylius.grids_extensions' key was not found in array
