### ISSUE TITLE
Join Translations on EntityFilterTypes

### ISSUE THREAD

**Issue by mamazu** [Sylius/SyliusGridBundle#309]
## The current state
Currently if I want to use the EntityFilter with a translatable entity I would create a configuration like so:
```yaml
        paymentMethod:
          type: 'entity'
          label: 'sylius.ui.payment_method'
          form_options:
            class: '%sylius.model.payment_method.class%'
            choice_label: translation
```

This will generate a filter for the Payment methods in my System. However, since the translations on those entity are lazy loaded, this means that if I have a couple of payment methods, it will lazy load the translations. This can be proven by not using a translatable attribute as a label but something like `code`.

## Possible solutions
My idea would be to add a join in the QueryBuilder for the `EntityType` if the loaded entity implements the ` Sylius\Component\Resource\Model\TranslatableInterface`. This however does not seem to have any effect on the loading of the label
