### ISSUE TITLE
BC break related to sorting in v1.14.0-ALPHA.1

### ISSUE THREAD

**Issue by dannyvw** [Sylius/SyliusGridBundle#369]
BC break in https://github.com/Sylius/SyliusGridBundle/pull/367/files

This configuration does not work anymore because sortable is always set to true in https://github.com/Sylius/SyliusGridBundle/pull/367/files#diff-28dd6bf4f3e5c7489778da4e9684b4f522616b8eb21b276b27af8882e4fc4479R29

```yaml
sylius_grid:
    grids:
        tag:
            sorting:
                name: 'asc'
            fields:
                name:
                    sortable: 'translation.name'
```
