### ISSUE TITLE
Unable to use Select filter with multiple values

### ISSUE THREAD

**Issue by macintoshplus** [Sylius/SyliusGridBundle#48]
I have configured a new grid for order with state filter. I want filter order with state in list.

Config:

```yaml
sylius_grid:
    grids:
        sylius_admin_order:
            filters:
                state:
                    type: select
                    form_options:
                        multiple: true
                        choices:
                            cart: cart
                            new: new
                            cancelled: cancelled
                            fulfilled: fulfilled
```

Result:

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; 
check the manual that corresponds to your MySQL server version for the right syntax to use near ' 
'fulfilled' ORDER BY s0_.number DESC LIMIT 10' at line 1
```
